# Generated by Django 5.0.7 on 2024-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventoryitemn_oversell_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_quantifiable',
            field=models.BooleanField(default=True),
        ),
    ]
