# Generated by Django 5.0.7 on 2024-07-23 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cashregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashregister'),
        ),
    ]
