# Generated by Django 5.0.7 on 2024-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_cash_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grandTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
