# Generated by Django 5.0.7 on 2024-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemn',
            name='oversell_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
