# Generated by Django 5.1 on 2024-08-25 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_grandtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='prepared_in',
            field=models.CharField(choices=[('1', 'Kitchen'), ('2', 'Bar'), ('3', 'Both')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='grandTotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
