# Generated by Django 5.1 on 2024-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_menucategory_prepared_in_alter_order_grandtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Preparing'), ('3', 'Ready'), ('4', 'CANCELED')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='to_be_prepared_in',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
